// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello
List rcpp_hello();
RcppExport SEXP _remeloc_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// locWindow_cpp
List locWindow_cpp(NumericMatrix coord, NumericVector local_reach, IntegerMatrix marginOrder, IntegerMatrix marginRank);
RcppExport SEXP _remeloc_locWindow_cpp(SEXP coordSEXP, SEXP local_reachSEXP, SEXP marginOrderSEXP, SEXP marginRankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coord(coordSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type local_reach(local_reachSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type marginOrder(marginOrderSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type marginRank(marginRankSEXP);
    rcpp_result_gen = Rcpp::wrap(locWindow_cpp(coord, local_reach, marginOrder, marginRank));
    return rcpp_result_gen;
END_RCPP
}
// orderCpp
IntegerVector orderCpp(NumericVector x);
RcppExport SEXP _remeloc_orderCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(orderCpp(x));
    return rcpp_result_gen;
END_RCPP
}
// orderStable
IntegerVector orderStable(NumericVector x);
RcppExport SEXP _remeloc_orderStable(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(orderStable(x));
    return rcpp_result_gen;
END_RCPP
}
// rankCpp
IntegerVector rankCpp(NumericVector x);
RcppExport SEXP _remeloc_rankCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rankCpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_remeloc_rcpp_hello", (DL_FUNC) &_remeloc_rcpp_hello, 0},
    {"_remeloc_locWindow_cpp", (DL_FUNC) &_remeloc_locWindow_cpp, 4},
    {"_remeloc_orderCpp", (DL_FUNC) &_remeloc_orderCpp, 1},
    {"_remeloc_orderStable", (DL_FUNC) &_remeloc_orderStable, 1},
    {"_remeloc_rankCpp", (DL_FUNC) &_remeloc_rankCpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_remeloc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
