# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_remeloc_rcpp_hello`)
}

allEdge_cpp <- function(coord, local_reach, marginOrder, marginRank) {
    .Call(`_remeloc_allEdge_cpp`, coord, local_reach, marginOrder, marginRank)
}

